const STORAGE_BASE = 'dukkan-kasa-v1';
const SHARED_STORAGE_KEY = 'dukkan-kasa-shared-v1';
const SHARED_MIGRATION_KEY = 'dukkan-kasa-shared-migrated-v1';
const AUTH_KEY = 'dukkan-kasa-users-v1';
const SESSION_KEY = 'dukkan-kasa-session';
const months = ['Ocak','Şubat','Mart','Nisan','Mayıs','Haziran','Temmuz','Ağustos','Eylül','Ekim','Kasım','Aralık'];
let currentUser = sessionStorage.getItem(SESSION_KEY) || '';
let authMode = 'login';
let records = [];
const $ = id => document.getElementById(id);
const money = value => new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY'}).format(Number(value)||0);
const n = id => Number($(id).value)||0;
const today = new Date();

function loadRecords(){ try { const data=JSON.parse(localStorage.getItem(SHARED_STORAGE_KEY)||'[]'); return Array.isArray(data)?data:[]; } catch { return []; } }
function saveRecords(){ localStorage.setItem(SHARED_STORAGE_KEY,JSON.stringify(records)); }
function loadUsers(){ try{return JSON.parse(localStorage.getItem(AUTH_KEY)||'[]')}catch{return []} }
function saveUsers(users){localStorage.setItem(AUTH_KEY,JSON.stringify(users));}
function ensureDefaultUser(){const users=loadUsers();if(users.some(u=>u.normalized==='omerfaruk'))return;users.push({username:'omerfaruk',normalized:'omerfaruk',salt:'d28653c400df3bdbcd33fa69383b8646',hash:'039cf99ff0ca2d0463e0f40eb0d6bdb491bbc2f764ad9f42e506b59cec0558c4',createdAt:Date.now(),isDefault:true});saveUsers(users);}
function migrateToSharedStorage(){if(localStorage.getItem(SHARED_MIGRATION_KEY))return;const combined=[];const add=data=>{if(!Array.isArray(data))return;for(const item of data){if(!combined.some(x=>x.id===item.id))combined.push(item)}};try{add(JSON.parse(localStorage.getItem(SHARED_STORAGE_KEY)||'[]'));add(JSON.parse(localStorage.getItem(STORAGE_BASE)||'[]'));for(const user of loadUsers())add(JSON.parse(localStorage.getItem(`${STORAGE_BASE}:${user.normalized}`)||'[]'));}catch{}localStorage.setItem(SHARED_STORAGE_KEY,JSON.stringify(combined));localStorage.setItem(SHARED_MIGRATION_KEY,'1');}
function bytesToHex(bytes){return [...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,'0')).join('');}
function hexToBytes(hex){return new Uint8Array(hex.match(/.{1,2}/g).map(b=>parseInt(b,16)));}
async function passwordHash(password,saltHex){const salt=saltHex?hexToBytes(saltHex):crypto.getRandomValues(new Uint8Array(16));const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:120000,hash:'SHA-256'},key,256);return {salt:bytesToHex(salt),hash:bytesToHex(bits)};}
function setAuthMode(mode){authMode=mode;const register=mode==='register';$('authTitle').textContent=register?'Yeni kullanıcı oluştur':'Hesabınıza giriş yapın';$('authSubtitle').textContent=register?'Bu cihazda kullanacağınız kullanıcı adı ve şifreyi belirleyin.':'Kasa kayıtlarınıza ulaşmak için kullanıcı adı ve şifrenizi girin.';$('confirmLabel').hidden=!register;$('authConfirm').required=register;$('authPassword').autocomplete=register?'new-password':'current-password';$('authSubmit').textContent=register?'Hesap Oluştur':'Giriş Yap';$('authToggle').textContent=register?'Zaten hesabım var':'Yeni kullanıcı oluştur';$('authError').textContent='';}
function openApp(username){currentUser=username;sessionStorage.setItem(SESSION_KEY,username);migrateToSharedStorage();records=loadRecords();$('authScreen').hidden=true;document.querySelectorAll('.app-shell').forEach(el=>el.hidden=false);$('currentUser').textContent=username;renderDashboard();renderTransactions();renderReport();}
function closeApp(){sessionStorage.removeItem(SESSION_KEY);currentUser='';records=[];document.querySelectorAll('.app-shell').forEach(el=>el.hidden=true);$('authScreen').hidden=false;$('authPassword').value='';$('authConfirm').value='';setAuthMode('login');}
function esc(text=''){ return String(text).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
function totals(list){ return list.reduce((a,r)=>{a.cash+=Number(r.cash)||0;a.pos+=Number(r.pos)||0;a.pos1+=Number(r.pos1)||0;a.online+=Number(r.online)||0;a.expense+=Number(r.expense)||0;return a},{cash:0,pos:0,pos1:0,online:0,expense:0}); }
function monthRecords(year,month){ return records.filter(r=>{const [y,m]=r.date.split('-').map(Number);return y===Number(year)&&m===Number(month)}); }
function toast(msg){ const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200); }
function showPage(id){ document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.page===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='dashboard')renderDashboard();if(id==='transactions')renderTransactions();if(id==='reports')renderReport(); }

function renderDashboard(){ const list=monthRecords($('dashYear').value,$('dashMonth').value);const t=totals(list);const revenue=t.cash+t.pos+t.pos1+t.online;const net=revenue-t.expense;$('kpiRevenue').textContent=money(revenue);$('kpiExpense').textContent=money(t.expense);$('kpiNet').textContent=money(net);$('kpiNet').classList.toggle('negative',net<0);$('kpiCount').textContent=list.length;$('cashTotal').textContent=money(t.cash);$('posTotal').textContent=money(t.pos);$('pos1Total').textContent=money(t.pos1);$('onlineTotal').textContent=money(t.online);const latest=[...list].sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt-a.createdAt).slice(0,5);$('recentList').innerHTML=latest.length?latest.map(r=>{const rev=(Number(r.cash)||0)+(Number(r.pos)||0)+(Number(r.pos1)||0)+(Number(r.online)||0),net=rev-(Number(r.expense)||0);return `<div class="recent-item"><div><strong>${esc(r.description||r.expenseItem||'İşlem')}</strong><small>${new Date(r.date+'T00:00:00').toLocaleDateString('tr-TR')}</small></div><strong class="${net<0?'negative':''}">${money(net)}</strong></div>`}).join(''):'<div class="empty">Bu ay için henüz kayıt yok.</div>'; }
function renderTransactions(){ const q=$('search').value.trim().toLocaleLowerCase('tr');const list=[...records].filter(r=>!q||[r.description,r.expenseItem,r.note,r.date].join(' ').toLocaleLowerCase('tr').includes(q)).sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt-a.createdAt);$('transactionRows').innerHTML=list.length?list.map(r=>{const rev=(Number(r.cash)||0)+(Number(r.pos)||0)+(Number(r.pos1)||0)+(Number(r.online)||0),net=rev-(Number(r.expense)||0);return `<tr><td>${new Date(r.date+'T00:00:00').toLocaleDateString('tr-TR')}</td><td><strong>${esc(r.description||'—')}</strong><br><small>${esc(r.note||'')}</small></td><td class="num money-in">${money(rev)}</td><td>${esc(r.expenseItem||'—')}</td><td class="num money-out">${money(r.expense)}</td><td class="num ${net<0?'negative':'money-in'}">${money(net)}</td><td><button class="delete-btn" data-delete="${r.id}">Sil</button></td></tr>`}).join(''):'<tr><td colspan="7" class="empty">Henüz işlem kaydı bulunmuyor.</td></tr>'; }
function renderReport(){ const year=Number($('reportYear').value);let annual={cash:0,pos:0,pos1:0,online:0,expense:0};$('reportRows').innerHTML=months.map((name,i)=>{const t=totals(monthRecords(year,i+1));annual.cash+=t.cash;annual.pos+=t.pos;annual.pos1+=t.pos1;annual.online+=t.online;annual.expense+=t.expense;const rev=t.cash+t.pos+t.pos1+t.online,net=rev-t.expense;return `<tr><td>${name}</td><td class="num">${money(t.cash)}</td><td class="num">${money(t.pos)}</td><td class="num">${money(t.pos1)}</td><td class="num">${money(t.online)}</td><td class="num money-in">${money(rev)}</td><td class="num money-out">${money(t.expense)}</td><td class="num ${net<0?'negative':'money-in'}">${money(net)}</td></tr>`}).join('');const rev=annual.cash+annual.pos+annual.pos1+annual.online,net=rev-annual.expense;$('reportTotal').innerHTML=`<tr><td>YIL TOPLAMI</td><td class="num">${money(annual.cash)}</td><td class="num">${money(annual.pos)}</td><td class="num">${money(annual.pos1)}</td><td class="num">${money(annual.online)}</td><td class="num">${money(rev)}</td><td class="num">${money(annual.expense)}</td><td class="num">${money(net)}</td></tr>`; }
function updateFormSummary(){ const rev=n('cash')+n('pos')+n('pos1')+n('online');$('formRevenue').textContent=money(rev);$('formNet').textContent=money(rev-n('expense')); }
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href);}
function backup(){download(`dukkan-kasa-yedek-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify({version:1,exportedAt:new Date().toISOString(),records},null,2),'application/json');toast('JSON yedeği indirildi.');}
function exportCsv(){const rows=[['Tarih','Açıklama','Nakit','POS / Kart','POS %1','Yemek Kartı / Online','Gider Kalemi','Gider','Not'],...records.map(r=>[r.date,r.description,r.cash,r.pos,r.pos1||0,r.online,r.expenseItem,r.expense,r.note])];download('dukkan-kasa-kayitlari.csv','\ufeff'+rows.map(row=>row.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(';')).join('\n'),'text/csv;charset=utf-8');toast('CSV dosyası indirildi.');}

months.forEach((m,i)=>$('dashMonth').add(new Option(m,i+1)));$('dashYear').value=today.getFullYear();$('dashMonth').value=today.getMonth()+1;$('reportYear').value=today.getFullYear();$('date').value=today.toISOString().slice(0,10);
document.querySelectorAll('.nav-btn').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.go)));['dashYear','dashMonth'].forEach(id=>$(id).addEventListener('change',renderDashboard));$('reportYear').addEventListener('change',renderReport);['cash','pos','pos1','online','expense'].forEach(id=>$(id).addEventListener('input',updateFormSummary));$('search').addEventListener('input',renderTransactions);
$('transactionForm').addEventListener('submit',e=>{e.preventDefault();const record={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),createdAt:Date.now(),date:$('date').value,description:$('description').value.trim(),cash:n('cash'),pos:n('pos'),pos1:n('pos1'),online:n('online'),expenseItem:$('expenseItem').value.trim(),expense:n('expense'),note:$('note').value.trim()};if(record.cash+record.pos+record.pos1+record.online+record.expense<=0){toast('En az bir tutar girin.');return}if(record.expense>0&&!record.expenseItem){toast('Gider kalemini yazın.');return}records.push(record);saveRecords();e.target.reset();$('date').value=record.date;updateFormSummary();renderTransactions();toast('İşlem kaydedildi.');});
$('transactionRows').addEventListener('click',e=>{const id=e.target.dataset.delete;if(!id)return;if(confirm('Bu kaydı silmek istediğinize emin misiniz?')){records=records.filter(r=>r.id!==id);saveRecords();renderTransactions();toast('Kayıt silindi.')}});
$('backupBtn').addEventListener('click',backup);$('backupBtn2').addEventListener('click',backup);$('exportCsvBtn').addEventListener('click',exportCsv);$('restoreBtn').addEventListener('click',()=>$('restoreInput').click());$('restoreInput').addEventListener('change',async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(!Array.isArray(data.records))throw Error();if(!confirm(`Yedekte ${data.records.length} kayıt var. Mevcut kayıtların üzerine yazılsın mı?`))return;records=data.records;saveRecords();renderDashboard();renderTransactions();renderReport();toast('Yedek başarıyla yüklendi.')}catch{toast('Geçerli bir yedek dosyası seçin.')}e.target.value='';});
$('authToggle').addEventListener('click',()=>setAuthMode(authMode==='login'?'register':'login'));
$('logoutBtn').addEventListener('click',()=>{if(confirm('Oturumu kapatmak istiyor musunuz?'))closeApp();});
$('authForm').addEventListener('submit',async e=>{e.preventDefault();const username=$('authUsername').value.trim();const password=$('authPassword').value;const normalized=username.toLocaleLowerCase('tr');const users=loadUsers();$('authError').textContent='';$('authSubmit').disabled=true;try{if(!/^[\p{L}\p{N}._-]{3,30}$/u.test(username)){throw new Error('Kullanıcı adı 3-30 karakter olmalı; harf, sayı, nokta, tire veya alt çizgi kullanılabilir.')}if(password.length<6)throw new Error('Şifre en az 6 karakter olmalıdır.');if(authMode==='register'){if(password!==$('authConfirm').value)throw new Error('Şifreler birbiriyle aynı değil.');if(users.some(u=>u.normalized===normalized))throw new Error('Bu kullanıcı adı zaten kayıtlı.');const result=await passwordHash(password);users.push({username,normalized,salt:result.salt,hash:result.hash,createdAt:Date.now()});saveUsers(users);openApp(username);toast('Hesap oluşturuldu. Ortak kasa açıldı.');}else{const user=users.find(u=>u.normalized===normalized);if(!user)throw new Error('Kullanıcı adı veya şifre hatalı.');const result=await passwordHash(password,user.salt);if(result.hash!==user.hash)throw new Error('Kullanıcı adı veya şifre hatalı.');openApp(user.username);toast('Giriş başarılı. Ortak kasa açıldı.');}}catch(err){$('authError').textContent=err.message;}finally{$('authSubmit').disabled=false;}});
ensureDefaultUser();setAuthMode('login');updateFormSummary();
if(currentUser&&loadUsers().some(u=>u.username===currentUser)){openApp(currentUser);}else{closeApp();}
